title: APIConfig
type: object
description: ''
properties:
  VoiceEnableDegradation:
    default: false
    description: 'Unknown, probably voice optimization testing'
    type: boolean
  VoiceEnableReceiverLimiting:
    default: true
    description: 'Unknown, probably voice optimization testing'
    type: boolean
  address:
    description: VRChat's office address
    minLength: 1
    type: string
  announcements:
    type: array
    description: Public Announcements
    uniqueItems: true
    minItems: 0
    items:
      $ref: ./APIConfigAnnouncement.yaml
  appName:
    default: VrChat
    deprecated: true
    description: Game name
    minLength: 1
    type: string
  availableLanguageCodes:
    description: List of supported Languages
    type: array
    items:
      type: string
  availableLanguages:
    description: List of supported Languages
    type: array
    items:
      type: string
  buildVersionTag:
    description: Build tag of the API server
    minLength: 1
    type: string
  clientApiKey:
    description: apiKey to be used for all other requests
    minLength: 1
    type: string
  clientBPSCeiling:
    default: 18432
    description: Unknown
    type: integer
  clientDisconnectTimeout:
    default: 30000
    description: Unknown
    type: integer
  clientNetDispatchThread:
    default: false
    description: Unknown
    type: boolean
  clientNetInThread:
    default: false
    description: Unknown
    type: boolean
  clientNetInThread2:
    default: false
    description: Unknown
    type: boolean
  clientNetInThreadMobile:
    default: false
    description: Unknown
    type: boolean
  clientNetInThreadMobile2:
    default: false
    description: Unknown
    type: boolean
  clientNetOutThread:
    default: false
    description: Unknown
    type: boolean
  clientNetOutThread2:
    default: false
    description: Unknown
    type: boolean
  clientNetOutThreadMobile:
    default: false
    description: Unknown
    type: boolean
  clientNetOutThreadMobile2:
    default: false
    description: Unknown
    type: boolean
  clientQR:
    default: 1
    description: Unknown
    type: integer
  clientReservedPlayerBPS:
    default: 7168
    description: Unknown
    type: integer
  clientSentCountAllowance:
    default: 15
    description: Unknown
    type: integer
  contactEmail:
    description: VRChat's contact email
    minLength: 1
    type: string
  copyrightEmail:
    description: VRChat's copyright-issues-related email
    minLength: 1
    type: string
  currentPrivacyVersion:
    default: 1
    description: Current version number of the Privacy Agreement
    type: integer
  currentTOSVersion:
    example: 7
    description: Current version number of the Terms of Service
    minimum: 0
    type: integer
  defaultAvatar:
    $ref: ./AvatarID.yaml
  deploymentGroup:
    $ref: ./DeploymentGroup.yaml
  devLanguageCodes:
   type: array
   description: Unknown
   items:
     type: string
  devSdkUrl:
    deprecated: true
    description: 'Link to download the development SDK, use downloadUrls instead'
    minLength: 1
    type: string
  devSdkVersion:
    deprecated: true
    description: Version of the development SDK
    minLength: 1
    type: string
  dis-countdown:
    description: 'Unknown, "dis" maybe for disconnect?'
    format: date-time
    type: string
  disableAVProInProton:
    default: false
    description: Unknown
    type: boolean
  disableAvatarCopying:
    default: false
    description: Toggles if copying avatars should be disabled
    type: boolean
  disableAvatarGating:
    default: false
    description: Toggles if avatar gating should be disabled. Avatar gating restricts uploading of avatars to people with the `system_avatar_access` Tag or `admin_avatar_access` Tag
    type: boolean
  disableCommunityLabs:
    default: false
    description: Toggles if the Community Labs should be disabled
    type: boolean
  disableCommunityLabsPromotion:
    default: false
    description: Toggles if promotion out of Community Labs should be disabled
    type: boolean
  disableEmail:
    default: false
    description: Unknown
    type: boolean
  disableCaptcha:
    default: true
    description: Unknown
    type: boolean
  disableEventStream:
    default: false
    description: Toggles if Analytics should be disabled.
    type: boolean
  disableFeedbackGating:
    default: false
    description: Toggles if feedback gating should be disabled. Feedback gating restricts submission of feedback (reporting a World or User) to people with the `system_feedback_access` Tag.
    type: boolean
  disableFrontendBuilds:
    default: false
    description: 'Unknown, probably toggles compilation of frontend web builds? So internal flag?'
    type: boolean
  disableHello:
    default: false
    description: Unknown
    type: boolean
  disableOculusSubs:
    default: false
    description: Toggles if signing up for Subscriptions in Oculus is disabled or not.
    type: boolean
  disableRegistration:
    default: false
    description: Toggles if new user account registration should be disabled.
    type: boolean
  disableSteamNetworking:
    default: true
    description: Toggles if Steam Networking should be disabled. VRChat these days uses Photon Unity Networking (PUN) instead.
    type: boolean
  disableTwoFactorAuth:
    default: false
    deprecated: true
    description: Toggles if 2FA should be disabled.
    type: boolean
  disableUdon:
    default: false
    description: Toggles if Udon should be universally disabled in-game.
    type: boolean
  disableUpgradeAccount:
    default: false
    description: Toggles if account upgrading "linking with Steam/Oculus" should be disabled.
    type: boolean
  downloadLinkWindows:
    description: Download link for game on the Oculus Rift website.
    minLength: 1
    type: string
  downloadUrls:
    $ref: ./APIConfigDownloadURLList.yaml
  dynamicWorldRows:
    description: 'Array of DynamicWorldRow objects, used by the game to display the list of world rows'
    minItems: 1
    type: array
    uniqueItems: true
    items:
      $ref: ./DynamicContentRow.yaml
  economyPauseEnd:
    description: Unknown
    type: string
  economyPauseStart:
    description: Unknown
    type: string
  economyState:
    default: 1
    description: Unknown
    type: integer
  events:
    $ref: ./APIConfigEvents.yaml
  homeWorldId:
    $ref: ./WorldID.yaml
  homepageRedirectTarget:
    default: 'https://hello.vrchat.com'
    description: Redirect target if you try to open the base API domain in your browser
    minLength: 1
    type: string
  hubWorldId:
    $ref: ./WorldID.yaml
  imageHostUrlList:
    description: A list of explicitly allowed origins that worlds can request images from via the Udon's [VRCImageDownloader#DownloadImage](https://creators.vrchat.com/worlds/udon/image-loading/#downloadimage).
    type: array
    items:
      type: string
  jobsEmail:
    description: VRChat's job application email
    minLength: 1
    type: string
  moderationEmail:
    description: VRChat's moderation related email
    minLength: 1
    type: string
  notAllowedToSelectAvatarInPrivateWorldMessage:
    description: Used in-game to notify a user they aren't allowed to select avatars in private worlds
    minLength: 1
    type: string
  sdkDeveloperFaqUrl:
    description: Link to the developer FAQ
    minLength: 1
    type: string
  sdkDiscordUrl:
    description: Link to the official VRChat Discord
    minLength: 1
    type: string
  sdkNotAllowedToPublishMessage:
    description: Used in the SDK to notify a user they aren't allowed to upload avatars/worlds yet
    minLength: 1
    type: string
  sdkUnityVersion:
    description: Unity version supported by the SDK
    minLength: 1
    type: string
  serverName:
    description: Server name of the API server currently responding
    minLength: 1
    type: string
  stringHostUrlList:
    description: A list of explicitly allowed origins that worlds can request strings from via the Udon's [VRCStringDownloader.LoadUrl](https://creators.vrchat.com/worlds/udon/string-loading/#ivrcstringdownload).
    type: array
    items:
      type: string
  supportEmail:
    description: VRChat's support email
    minLength: 1
    type: string
  timeOutWorldId:
    $ref: ./WorldID.yaml
  tutorialWorldId:
    $ref: ./WorldID.yaml
  updateRateMsMaximum:
    description: Unknown
    type: integer
  updateRateMsMinimum:
    description: Unknown
    type: integer
  updateRateMsNormal:
    description: Unknown
    type: integer
  updateRateMsUdonManual:
    description: Unknown
    type: integer
  uploadAnalysisPercent:
    description: Unknown
    type: integer
  urlList:
    description: List of allowed URLs that bypass the "Allow untrusted URL's" setting in-game
    type: array
    items:
      type: string
  useReliableUdpForVoice:
    default: false
    description: Unknown
    type: boolean
  viveWindowsUrl:
    description: Download link for game on the Steam website.
    minLength: 1
    type: string
  whiteListedAssetUrls:
    description: List of allowed URLs that are allowed to host avatar assets
    type: array
    items:
      type: string
  player-url-resolver-version:
    description: Currently used youtube-dl.exe version
    minLength: 1
    type: string
  player-url-resolver-sha1:
    description: Currently used youtube-dl.exe hash in SHA1-delimited format
    minLength: 1
    type: string
required:
  - VoiceEnableDegradation
  - VoiceEnableReceiverLimiting
  - address
  - announcements
  - appName
  - availableLanguageCodes
  - availableLanguages
  - buildVersionTag
  - clientApiKey
  - clientBPSCeiling
  - clientDisconnectTimeout
  - clientReservedPlayerBPS
  - clientSentCountAllowance
  - contactEmail
  - copyrightEmail
  - currentTOSVersion
  - defaultAvatar
  - deploymentGroup
  - devSdkUrl
  - devSdkVersion
  - dis-countdown
  - disableAvatarCopying
  - disableAvatarGating
  - disableCommunityLabs
  - disableCommunityLabsPromotion
  - disableEmail
  - disableEventStream
  - disableFeedbackGating
  - disableFrontendBuilds
  - disableHello
  - disableOculusSubs
  - disableRegistration
  - disableSteamNetworking
  - disableTwoFactorAuth
  - disableUdon
  - disableUpgradeAccount
  - downloadLinkWindows
  - downloadUrls
  - dynamicWorldRows
  - events
  - homeWorldId
  - homepageRedirectTarget
  - hubWorldId
  - imageHostUrlList
  - jobsEmail
  - moderationEmail
  - notAllowedToSelectAvatarInPrivateWorldMessage
  - sdkDeveloperFaqUrl
  - sdkDiscordUrl
  - sdkNotAllowedToPublishMessage
  - sdkUnityVersion
  - serverName
  - stringHostUrlList
  - supportEmail
  - timeOutWorldId
  - tutorialWorldId
  - updateRateMsMaximum
  - updateRateMsMinimum
  - updateRateMsNormal
  - updateRateMsUdonManual
  - uploadAnalysisPercent
  - urlList
  - useReliableUdpForVoice
  - viveWindowsUrl
  - whiteListedAssetUrls
  - player-url-resolver-version
  - player-url-resolver-sha1
